export const browserCoreExamples = [
  "dexter browser status",
  "dexter browser start",
  "dexter browser stop",
  "dexter browser tabs",
  "dexter browser open https://example.com",
  "dexter browser focus abcd1234",
  "dexter browser close abcd1234",
  "dexter browser screenshot",
  "dexter browser screenshot --full-page",
  "dexter browser screenshot --ref 12",
  "dexter browser snapshot",
  "dexter browser snapshot --format aria --limit 200",
  "dexter browser snapshot --efficient",
  "dexter browser snapshot --labels",
];

export const browserActionExamples = [
  "dexter browser navigate https://example.com",
  "dexter browser resize 1280 720",
  "dexter browser click 12 --double",
  'dexter browser type 23 "hello" --submit',
  "dexter browser press Enter",
  "dexter browser hover 44",
  "dexter browser drag 10 11",
  "dexter browser select 9 OptionA OptionB",
  "dexter browser upload /tmp/openclaw/uploads/file.pdf",
  'dexter browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "dexter browser dialog --accept",
  'dexter browser wait --text "Done"',
  "dexter browser evaluate --fn '(el) => el.textContent' --ref 7",
  "dexter browser console --level error",
  "dexter browser pdf",
];
